version: "3"
services:
  jenkins:
    image: qiaodapei/jenkins:alpine-2.164.3 
    container_name: jenkins
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/data/jenkins_home
      - /data/backup/jenkins:/data/jenkins_backup
    networks:
      - xunce
networks:
  xunce: 
